== Classes:

....
+--------+                    +--------+         +--------+
| layout +------------------->+ figure +-------->+ uimenu |
+----+---+                    ++--+-+--+         +--------+
     |                         ^  | |
     |    +------------+       |  | |
     |    | Constrains +-------+  | |
     |    +-+----------+          | |     +------+       +----------+
     |      |                     | +---->+ Axes +------>+ Plotting |
     |      |  +-----------+      |       +----+-+       +----------+
     |      +->+ uicontrol +<-----+            ^
     |         +---+-----+-+                   |
     |             |     |                     |
     |             |     +---------------------+
     |             |
     |             v
     |       +-----+-+
     +------>+ frame |                          made by
             +-------+                        asciiflow.com
....

=== figure

==== Methods:

===== Constructor:

[source,scilab]
----
f = figure(<num>, "PropertyName_1", PropertyValue_1, ... , "PropertyName_N", PropertyValue_N);
----

`createWindow()`

`close()`

`gcf()`

`gdf`

`scf`

==== Properties:

https://help.scilab.org/doc/5.5.2/en_US/figure_properties.html

=== uicontrol

==== Constructor:

[source,scilab]
----
h = uicontrol(parent, PropertyName, PropertyValue, ...);
----

https://help.scilab.org/docs/5.3.2/en_US/uicontrol.html

== Properties:

https://help.scilab.org/doc/5.5.2/en_US/uicontrol_properties.html

=== Styles:

* *Edit*
* *Frame*
* *Image*
* *Layer*
* *Listbox*
* *Popupmenu*
* *Pushbutton*
* *Radiobutton*
* *Slider*
* *Spinner*
* *Tab*
* *Table*
* *Text*
* *Checkbox*

[cols="^,^,^,^,^,^,^,^,^,^,^,^,^,^,^", options="header"]
|===
| |checkbox |edit |frame |image |layer |listbox |popupmenue |pushbutton |radiobutton |slider |spinner |tab |table |text
| |         |     |      |✓     |✗     |        |           |           |            |       |        |    |      |

| | | | | | | | | | | | | | |
|===

== Axes

=== Methods:

==== Constructor:

[source,scilab]
----
a = newaxes(h);
----

`gda`

`gca`

=== Properties:

https://help.scilab.org/doc/5.5.2/en_US/axes_properties.html

== uimenu

addmenu, delmenu, setmenu, or unsetmenu


 * x_message --> to open a popupmessage window
 * x_choose --> to perform a selection in a predefined list
 * x_dialog --> opens a dialog to get a response from the user as a Scilab string
 * x_choices --> to select a set of items each one being chosen through a togglelist
 * x_mdialog --> for a set ofx_dialog-like interactions or for acquiring amatrix
 * xgetfile --> a dialog used to get a file path


 * xclick
 * xgetmouse
 * seteventhandler

== Constraints

tlist

=== Constructor:

[source,scilab]
----
c = createConstraints(constraintsType, varargin);
----


== Layout

tlist

=== Constructor:

[source,scilab]
----
lay_opt = createLayoutOptions("border", padding);
----

== Border

tlist

=== Constructor:

[source,scilab]
----
border = createBorder(borderType, varargin);
----

== Functions:

`findobj`

`set`

https://help.scilab.org/doc/5.5.2/en_US/console_properties.html

`get`

`saveGui`

`loadGui`
